# Generated by Django 5.2.15 on 2026-07-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles_permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='access_admin_panel',
            field=models.BooleanField(default=False),
        ),
    ]
