# Generated by Django 5.2.15 on 2026-07-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles_permissions', '0002_roles_access_admin_panel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissions',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='permissions',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='updated_at',
        ),
    ]
