# Generated by Django 5.2.15 on 2026-07-09 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe')], default='stripe', max_length=50)),
                ('payment_intent', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('checkout_session_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('usd', 'USD'), ('pkr', 'PKR'), ('Inr', 'INR')], default='pkr', max_length=30)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('refunded', 'Refunded'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=100)),
                ('stripe_response', models.JSONField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
